version: '3.3'

networks:
  web:
    external: true

services:
  otp:
    build: .
    image: mapcentia/otp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
      labels:
        - traefik.backend=otp.vidi.gc2.io
        - traefik.frontend.rule=Host:otp.vidi.gc2.io # SET HOST
        - traefik.port=8888
        - traefik.backend.loadbalancer.swarm=true
        - traefik.docker.network=web
        - traefik.frontend.passHostHeader=true
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
